server:
  port: 12345

spring:
  application:
    name: banking-app
  datasource:
    url: jdbc:mysql://localhost:3306/banking_app
    username: root
    password: Root@12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

